data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'DLHLP'                         # Specify corpus
    path: '/work/b07u1234/b07701209/DLHLP'
    dev_split: ['dev']
    test_split: ['test']
    bucketing: False
    batch_size: 1
src:
  config: '/work/b07u1234/b07701209/E2E_ASR_TWCC/config/dlhlp_asr_best3.yaml'
  ckpt: '/work/b07u1234/b07701209/model_dir/ckpt/strong_trial_best3/best_att_dev.pth'

decode:
  beam_size: 1
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: '/data/storage/harry/test_env/dlhlp_ckpt/hw1_best_ppx.pth'
  lm_config: 'config/dlhlp_lm.yaml'
  lm_weight: 0.7
  ctc_weight: 0
